import type { User, Client, Quotation, Project, Task, ActivityLog, ContentItem, Reminder } from '@/types'

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    full_name: 'Muhassin Rahim',
    email: 'muhassin@emac.one',
    role: 'owner',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-2',
    full_name: 'Anees Rahman',
    email: 'anees@emac.one',
    role: 'admin',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    created_at: '2026-01-02T00:00:00Z',
    updated_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'usr-3',
    full_name: 'Jithin',
    email: 'jithin@emac.one',
    role: 'employee',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    created_at: '2026-01-03T00:00:00Z',
    updated_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'usr-4',
    full_name: 'Hashim',
    email: 'hashim@emac.one',
    role: 'employee',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    created_at: '2026-01-04T00:00:00Z',
    updated_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'usr-5',
    full_name: 'David',
    email: 'freelancer@emac.one',
    role: 'freelancer',
    status: 'active',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z',
  },
]

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    company_name: 'iDesignAds',
    contact_name: 'Rohit Verma',
    email: 'rohit@idesignads.com',
    phone: '+91 98450 11223',
    website: 'https://idesignads.com',
    address: 'Cyber City, Sector 29, Gurugram, India',
    industry: 'Performance Ads & Media',
    status: 'won',
    notes: 'Performance marketing agency focusing on Google Search & Display PPC alongside multi-channel social growth.',
    drive_url: 'https://drive.google.com/drive/folders/emac-idesignads',
    currency: 'INR',
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'cli-2',
    company_name: 'Ziegent',
    contact_name: 'Nikhil Menon',
    email: 'nikhil@ziegent.com',
    phone: '+91 97420 88990',
    website: 'https://ziegent.com',
    address: 'Infopark Phase 2, Kochi, Kerala, India',
    industry: 'Enterprise Tech & Branding',
    status: 'in_progress',
    notes: 'Corporate rebranding, custom interactive web platform, and full digital marketing funnel.',
    drive_url: 'https://drive.google.com/drive/folders/emac-ziegent',
    currency: 'INR',
    created_at: '2026-08-03T10:30:00Z',
    updated_at: '2026-08-03T10:30:00Z',
  },
  {
    id: 'cli-3',
    company_name: 'Liwaspring',
    contact_name: 'Fahad Al-Marzooqi',
    email: 'fahad@liwaspring.com',
    phone: '+971 4 883 4590',
    website: 'https://liwaspring.com',
    address: 'Al Quoz Industrial Area 3, Dubai, UAE',
    industry: 'Beverage & E-Commerce',
    status: 'won',
    notes: 'Premium natural spring water brand undergoing a modern e-commerce storefront revamp with custom subscription management.',
    drive_url: 'https://drive.google.com/drive/folders/emac-liwaspring',
    currency: 'AED',
    created_at: '2026-08-05T14:15:00Z',
    updated_at: '2026-08-05T14:15:00Z',
  },
  {
    id: 'cli-4',
    company_name: 'Opar',
    contact_name: 'Ananya Nair',
    email: 'ananya@oparstudio.com',
    phone: '+91 99800 44556',
    website: 'https://oparstudio.com',
    address: 'Indiranagar 100ft Road, Bangalore, India',
    industry: 'Lifestyle & Fashion Retail',
    status: 'won',
    notes: 'Luxury apparel and lifestyle studio requiring brand website development, monthly content planning, and viral social media reels.',
    drive_url: 'https://drive.google.com/drive/folders/emac-opar',
    currency: 'INR',
    created_at: '2026-08-08T09:00:00Z',
    updated_at: '2026-08-08T09:00:00Z',
  },
]

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'q-1',
    client_id: 'cli-1',
    quotation_number: 'QT-EMAC-2026-001',
    amount: 350000,
    advance_received: 175000,
    balance: 175000,
    status: 'approved',
    remarks: 'Google Ads PPC management + Monthly Social Media Campaign sprint. 50% advance confirmed.',
    drive_url: 'https://drive.google.com/file/d/emac-qt-001/view',
    currency: 'INR',
    payments: [
      {
        id: 'pay-101',
        quotation_id: 'q-1',
        amount: 175000,
        payment_date: '2026-08-02',
        payment_method: 'Bank Transfer (NEFT)',
        notes: 'Initial 50% advance received on contract signing.',
        created_at: '2026-08-02T09:00:00Z',
        created_by: 'Anees Rahman',
      },
    ],
    created_at: '2026-08-01T11:00:00Z',
    updated_at: '2026-08-02T09:00:00Z',
  },
  {
    id: 'q-2',
    client_id: 'cli-2',
    quotation_number: 'QT-EMAC-2026-002',
    amount: 580000,
    advance_received: 290000,
    balance: 290000,
    status: 'approved',
    remarks: 'Full Branding Identity System, Custom Web Development, and Digital Strategy Funnel.',
    drive_url: 'https://drive.google.com/file/d/emac-qt-002/view',
    currency: 'INR',
    payments: [
      {
        id: 'pay-102',
        quotation_id: 'q-2',
        amount: 290000,
        payment_date: '2026-08-04',
        payment_method: 'RTGS',
        notes: 'Phase 1 advance payment received.',
        created_at: '2026-08-04T12:00:00Z',
        created_by: 'Muhassin Rahim',
      },
    ],
    created_at: '2026-08-03T14:00:00Z',
    updated_at: '2026-08-04T12:00:00Z',
  },
  {
    id: 'q-3',
    client_id: 'cli-3',
    quotation_number: 'QT-EMAC-2026-003',
    amount: 24000,
    advance_received: 12000,
    balance: 12000,
    status: 'approved',
    remarks: 'E-Commerce Storefront Revamp, Custom Subscription Engine & UX Overhaul.',
    drive_url: 'https://drive.google.com/file/d/emac-qt-003/view',
    currency: 'AED',
    payments: [
      {
        id: 'pay-103',
        quotation_id: 'q-3',
        amount: 12000,
        payment_date: '2026-08-06',
        payment_method: 'Wire Transfer',
        notes: '50% project kickoff milestone received.',
        created_at: '2026-08-06T10:00:00Z',
        created_by: 'Anees Rahman',
      },
    ],
    created_at: '2026-08-05T16:00:00Z',
    updated_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'q-4',
    client_id: 'cli-4',
    quotation_number: 'QT-EMAC-2026-004',
    amount: 240000,
    advance_received: 120000,
    balance: 120000,
    status: 'approved',
    remarks: 'Brand Website Design & Development + Social Media Content Retainer.',
    drive_url: 'https://drive.google.com/file/d/emac-qt-004/view',
    currency: 'INR',
    payments: [
      {
        id: 'pay-104',
        quotation_id: 'q-4',
        amount: 120000,
        payment_date: '2026-08-09',
        payment_method: 'Bank Transfer (IMPS)',
        notes: 'Advance retainer and website design phase kickoff.',
        created_at: '2026-08-09T15:30:00Z',
        created_by: 'Muhassin Rahim',
      },
    ],
    created_at: '2026-08-08T10:00:00Z',
    updated_at: '2026-08-09T15:30:00Z',
  },
]

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-1',
    client_id: 'cli-1',
    name: 'Google Ads Funnel & Social Media Marketing',
    description: 'High-converting Google Search & Display PPC campaigns, audience segmentation, and monthly multi-platform social creative production.',
    priority: 'high',
    status: 'in_progress',
    start_date: '2026-08-01',
    due_date: '2026-10-31',
    drive_url: 'https://drive.google.com/drive/folders/emac-prj-idesignads',
    enable_content_planner: true,
    content_planner_share_token: 'idesignads-growth-2026',
    client_permissions: {
      allow_approval: true,
      allow_comments: true,
      allow_rescheduling: true,
    },
    members: [INITIAL_USERS[0], INITIAL_USERS[1], INITIAL_USERS[3]],
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prj-2',
    client_id: 'cli-2',
    name: 'Branding Identity, Website & Digital Marketing',
    description: 'Comprehensive brand typography, color system, 3D asset kit, custom web platform development, and B2B digital acquisition funnel.',
    priority: 'critical',
    status: 'in_progress',
    start_date: '2026-08-05',
    due_date: '2026-11-15',
    drive_url: 'https://drive.google.com/drive/folders/emac-prj-ziegent',
    enable_content_planner: false,
    members: [INITIAL_USERS[0], INITIAL_USERS[2], INITIAL_USERS[3], INITIAL_USERS[4]],
    created_at: '2026-08-05T00:00:00Z',
    updated_at: '2026-08-05T00:00:00Z',
  },
  {
    id: 'prj-3',
    client_id: 'cli-3',
    name: 'E-Commerce Storefront & Modern Website Revamp',
    description: 'Revamping the digital storefront with blazing fast performance, seamless subscription delivery scheduling, and intuitive product catalog.',
    priority: 'high',
    status: 'in_progress',
    start_date: '2026-08-10',
    due_date: '2026-10-20',
    drive_url: 'https://drive.google.com/drive/folders/emac-prj-liwaspring',
    enable_content_planner: false,
    members: [INITIAL_USERS[1], INITIAL_USERS[2], INITIAL_USERS[4]],
    created_at: '2026-08-10T00:00:00Z',
    updated_at: '2026-08-10T00:00:00Z',
  },
  {
    id: 'prj-4',
    client_id: 'cli-4',
    name: 'Social Media Management & Brand Website',
    description: 'Curated aesthetic content calendar, weekly viral reels strategy, influencer partnerships, and responsive luxury brand showcase website.',
    priority: 'high',
    status: 'in_progress',
    start_date: '2026-08-12',
    due_date: '2026-11-30',
    drive_url: 'https://drive.google.com/drive/folders/emac-prj-opar',
    enable_content_planner: true,
    content_planner_share_token: 'opar-social-showcase-2026',
    client_permissions: {
      allow_approval: true,
      allow_comments: true,
      allow_rescheduling: true,
    },
    members: [INITIAL_USERS[0], INITIAL_USERS[2], INITIAL_USERS[3]],
    created_at: '2026-08-12T00:00:00Z',
    updated_at: '2026-08-12T00:00:00Z',
  },
]

export const INITIAL_CONTENT_ITEMS: ContentItem[] = [
  {
    id: 'cnt-1',
    project_id: 'prj-1',
    title: 'High-Converting Google Search Ads Strategy',
    platform: 'linkedin',
    content_type: 'carousel',
    scheduled_date: '2026-08-28',
    scheduled_time: '10:00 AM',
    assigned_to: 'usr-4',
    caption: 'How iDesignAds scaled ROAS to 4.8x using high-intent negative keyword grouping and responsive search ads. 📈🚀',
    drive_url: 'https://drive.google.com/file/d/emac-content-idesignads-1/view',
    status: 'approved',
    notes: 'Approved by Rohit Verma.',
    annotations: [
      {
        id: 'ann-1',
        content_item_id: 'cnt-1',
        author_name: 'Rohit Verma (Client)',
        author_role: 'client',
        comment: 'The carousel flow looks sharp and the ROAS numbers are accurately represented. Approved for publishing!',
        status: 'resolved',
        created_at: '2026-08-27T12:00:00Z',
      },
    ],
    created_at: '2026-08-25T10:00:00Z',
    updated_at: '2026-08-27T12:00:00Z',
  },
  {
    id: 'cnt-2',
    project_id: 'prj-4',
    title: 'Opar Autumn Collection - Teaser Reel',
    platform: 'instagram',
    content_type: 'reel',
    scheduled_date: '2026-08-29',
    scheduled_time: '05:30 PM',
    assigned_to: 'usr-3',
    caption: 'Unveiling timeless luxury. The new Autumn/Winter aesthetic drops this Friday exclusively at Opar Studio. ✨👗',
    drive_url: 'https://drive.google.com/file/d/emac-content-opar-reel/view',
    status: 'revision_requested',
    notes: 'Reviewing color grading and music sync.',
    annotations: [
      {
        id: 'ann-2',
        content_item_id: 'cnt-2',
        author_name: 'Ananya Nair (Client)',
        author_role: 'client',
        comment: 'Can we switch the background audio track to a softer ambient beat and lengthen the closing logo reveal by 1 second?',
        suggested_drive_url: 'https://drive.google.com/file/d/emac-audio-suggestion/view',
        status: 'open',
        created_at: '2026-08-28T09:30:00Z',
      },
    ],
    created_at: '2026-08-26T14:00:00Z',
    updated_at: '2026-08-28T09:30:00Z',
  },
  {
    id: 'cnt-3',
    project_id: 'prj-4',
    title: 'Behind the Craft: Opar Sustainable Fabrics',
    platform: 'instagram',
    content_type: 'post',
    scheduled_date: '2026-08-31',
    scheduled_time: '11:15 AM',
    assigned_to: 'usr-4',
    caption: '100% organic, hand-spun textiles crafted with care for people and planet.',
    drive_url: 'https://drive.google.com/file/d/emac-content-opar-fabrics/view',
    status: 'writing',
    notes: 'Drafting caption copy and selecting top 3 high-res studio photographs.',
    created_at: '2026-08-27T11:00:00Z',
    updated_at: '2026-08-27T11:00:00Z',
  },
  {
    id: 'cnt-4',
    project_id: 'prj-1',
    title: 'September PPC Growth Insights Newsletter #12',
    platform: 'email',
    content_type: 'newsletter',
    scheduled_date: '2026-09-02',
    scheduled_time: '08:00 AM',
    assigned_to: 'usr-2',
    caption: 'Performance Advertising benchmarks, AI bidding strategies, and ad copy templates for Q4.',
    drive_url: 'https://drive.google.com/file/d/emac-content-newsletter/view',
    status: 'draft',
    notes: 'Content outline ready, pending banner asset from design team.',
    created_at: '2026-08-28T15:00:00Z',
    updated_at: '2026-08-28T15:00:00Z',
  },
]

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    project_id: 'prj-1',
    assigned_to: 'usr-4',
    title: 'Google Ads campaign setup & keyword intent clustering',
    description: 'Structure search ad groups with exact/phrase matches and negative keywords list.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-09-02',
    order_index: 1,
    created_at: '2026-08-02T00:00:00Z',
    updated_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'tsk-2',
    project_id: 'prj-1',
    assigned_to: 'usr-2',
    title: 'Performance analytics & GA4 conversion event tracking',
    description: 'Verify server-side GTM events and custom conversion tracking for lead submissions.',
    priority: 'medium',
    status: 'todo',
    due_date: '2026-09-05',
    order_index: 2,
    created_at: '2026-08-02T00:00:00Z',
    updated_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'tsk-3',
    project_id: 'prj-2',
    assigned_to: 'usr-3',
    title: 'Ziegent brand guideline manual & typography hierarchy',
    description: 'Finalize brand book covering primary mark, typography, HSL color tokens, and icon styles.',
    priority: 'critical',
    status: 'completed',
    due_date: '2026-08-26',
    completed_at: '2026-08-26T15:00:00Z',
    is_archived: false,
    order_index: 1,
    created_at: '2026-08-06T00:00:00Z',
    updated_at: '2026-08-26T15:00:00Z',
  },
  {
    id: 'tsk-4',
    project_id: 'prj-2',
    assigned_to: 'usr-4',
    title: 'Corporate website frontend architecture & animations',
    description: 'Build responsive Next.js/React layouts with fluid micro-interactions and SEO schema.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-09-10',
    order_index: 2,
    created_at: '2026-08-07T00:00:00Z',
    updated_at: '2026-08-07T00:00:00Z',
  },
  {
    id: 'tsk-5',
    project_id: 'prj-3',
    assigned_to: 'usr-5',
    title: 'Liwaspring e-commerce subscription checkout integration',
    description: 'Implement weekly/monthly water bottle subscription selector and cart discounts.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-09-08',
    order_index: 1,
    created_at: '2026-08-11T00:00:00Z',
    updated_at: '2026-08-11T00:00:00Z',
  },
  {
    id: 'tsk-6',
    project_id: 'prj-3',
    assigned_to: 'usr-3',
    title: 'Product catalog photography & UI component system',
    description: 'Design interactive bottle size selectors, nutrition info cards, and bundle deals.',
    priority: 'medium',
    status: 'todo',
    due_date: '2026-09-12',
    order_index: 2,
    created_at: '2026-08-11T00:00:00Z',
    updated_at: '2026-08-11T00:00:00Z',
  },
  {
    id: 'tsk-7',
    project_id: 'prj-4',
    assigned_to: 'usr-3',
    title: 'Opar responsive website design prototype in Figma',
    description: 'Design luxury lookbook layout, product detail cards, and store locator grid.',
    priority: 'critical',
    status: 'review',
    due_date: '2026-08-30',
    order_index: 1,
    created_at: '2026-08-13T00:00:00Z',
    updated_at: '2026-08-13T00:00:00Z',
  },
  {
    id: 'tsk-8',
    project_id: 'prj-4',
    assigned_to: 'usr-4',
    title: 'Weekly reels storyboard & influencer outreach list',
    description: 'Shortlist 15 fashion influencers and create 4 video concept moodboards.',
    priority: 'medium',
    status: 'todo',
    due_date: '2026-09-04',
    order_index: 2,
    created_at: '2026-08-13T00:00:00Z',
    updated_at: '2026-08-13T00:00:00Z',
  },
]

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    entity_type: 'project',
    entity_id: 'prj-2',
    action: 'status_change',
    details: 'Project "Branding Identity, Website & Digital Marketing" moved to In Progress',
    user_id: 'usr-1',
    user_name: 'Muhassin Rahim',
    created_at: '2026-08-05T10:00:00Z',
  },
  {
    id: 'act-2',
    entity_type: 'task',
    entity_id: 'tsk-3',
    action: 'status_change',
    details: 'Task "Ziegent brand guideline manual & typography hierarchy" marked as Completed',
    user_id: 'usr-3',
    user_name: 'Jithin',
    created_at: '2026-08-26T15:00:00Z',
  },
  {
    id: 'act-3',
    entity_type: 'quotation',
    entity_id: 'q-1',
    action: 'update',
    details: 'Advance payment of ₹175,000 recorded for quotation QT-EMAC-2026-001',
    user_id: 'usr-2',
    user_name: 'Anees Rahman',
    created_at: '2026-08-02T09:00:00Z',
  },
]

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    title: 'iDesignAds - Q3 PPC Scaling & Ad Budget Review',
    date: '2026-08-30',
    time: '03:00 PM',
    type: 'call',
    priority: 'high',
    assigned_to: 'usr-1',
    notes: 'Review Google Ads CPC metrics, conversion rate optimization, and expand social media budget.',
    client_id: 'cli-1',
    project_id: 'prj-1',
    is_completed: false,
    created_at: '2026-08-26T10:00:00Z',
    updated_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 'rem-2',
    title: 'Ziegent Brand Book Final Client Presentation',
    date: '2026-08-31',
    time: '11:00 AM',
    type: 'meeting',
    priority: 'high',
    assigned_to: 'usr-3',
    notes: 'Walkthrough brand typography, 3D asset render library, and website sitemap with Nikhil Menon.',
    client_id: 'cli-2',
    project_id: 'prj-2',
    is_completed: false,
    created_at: '2026-08-27T09:00:00Z',
    updated_at: '2026-08-27T09:00:00Z',
  },
  {
    id: 'rem-3',
    title: 'Liwaspring E-Commerce Milestone 2 Follow-Up',
    date: '2026-09-01',
    time: '02:30 PM',
    type: 'followup',
    priority: 'medium',
    assigned_to: 'usr-2',
    notes: 'Check in on subscription engine testing and payment gateway approvals with Dubai team.',
    client_id: 'cli-3',
    project_id: 'prj-3',
    is_completed: false,
    created_at: '2026-08-28T08:00:00Z',
    updated_at: '2026-08-28T08:00:00Z',
  },
]
